stages:
  - build
  - test
  - deploy
  - clean

build_image:
  stage: build
  script:
    - echo $CI_COMMIT_SHA > commitsha
    - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID .

run_tests:
  stage: test
  script:
    - docker run $CI_REGISTRY_IMAGE npm run code-coverage

registry_deployment:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest && docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
    - docker logout $CI_REGISTRY
  only:
    refs:
      - master


remove_images:
  stage: clean
  script:
    - docker rmi $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  when: always
