variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE/v2/$CI_COMMIT_REF_SLUG"
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: test-pass
    POSTGRES_DB: testdb
    MONGO_CONN: "mongodb://mongo:27017/dataplatform"
    MONGO_TIMEOUT: 60000
    APIARY_NAME: "golemioapi"
    APIARY_NAME_DEV: "outputgatewaydev"
    HOST_URL: "https://api.golemio.cz/v2"
    HOST_URL_DEV: "http://rabin.golemio.cz/v2"
    HELM_NAME: "golemio"
    K8S_DEPLOYMENT_NAME: output-gateway-v2
    K8S_DEPLOYMENT_IMAGE_TAG: $CI_PIPELINE_ID

cache:
    key:
        files:
            - package-lock.json
    paths:
        - node_modules

stages:
    - pre-test
    - test
    - build
    - release
    - deploy

include:
    - template: "Workflows/Branch-Pipelines.gitlab-ci.yml"
    - project: "operator-ict/devops/gitlab-ci-pipeline"
      file:
          - "/docker/simple-build.yml"
          - "/k8s-golemio/helm-golemio-deploy.yml"
          - "/apiary/blueprint.yml"
          - "/docs/golemio-gitlab-docs-pages.yml"
          - "/npm/bump-dependencies.yml"

.run_tests:
    stage: test
    image: registry.gitlab.com/operator-ict/golemio/devops/docker-node-env/master:latest
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
    services:
        - name: postgis/postgis:13-3.2-alpine
          alias: postgres
        - name: mvertes/alpine-mongo:4.0.5-0
          alias: mongo
        - redis:6.2-alpine
    script:
        - npm install --ignore-scripts --progress=false
        # Audit production dependencies for HIGH vulnerabilities
        - npm audit --omit dev --audit-level high
        - npm run lint
        - npm run build-apidocs
        - npm run build
        - export LOG_LEVEL=INFO
        - export MONGO_CONN=$MONGO_CONN
        - export POSTGRES_CONN=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB
        - export SENTRY_ENABLE=false
        - export REDIS_ENABLE=true
        - export REDIS_CONN=redis://redis/
        - export SQL_DUMP_FILES=node_modules/@golemio/*/db/example/*.sql
        - export MONGO_DATA_PATHS=node_modules/@golemio/*/db/example/mongo_data
        - export POSTGRES_MIGRATIONS_DIR=node_modules/@golemio/*/db/migrations/**/postgresql
        # Run migrations from schema definitions
        - export SCH_NPM_TAG="dev" && [[ "$CI_COMMIT_REF_NAME" == "master" ]] && export SCH_NPM_TAG="latest"
        - export SCH_VERSION=$(npm show @golemio/schema-definitions@$SCH_NPM_TAG version)
        - export SCH_DIR=$(mktemp -d)
        - echo "Installing schema-definitions version $SCH_VERSION"
        - npm install --ignore-scripts --no-audit --prefix $SCH_DIR @golemio/schema-definitions@$SCH_VERSION
        - sh -c "cd $SCH_DIR/node_modules/@golemio/schema-definitions && npm run migrate-postgres-db >/dev/null && cd -"
        # Run migrations from modules
        - npx golemio migrate-db up --silent
        # Import postgres test data
        - npx golemio import-db-data
        # Import mongo test data (the old way)
        - unset SQL_DUMP_FILES
        - npx golemio-import-test-data
        - npm run code-coverage
        - npm run dredd
    tags:
        - docker
    rules:
        - if: $SKIP_TEST_AND_STAGES_AFTER
          when: never
        - when: always
    artifacts:
        when: always
        reports:
            junit: junit.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage/cobertura-coverage.xml

run_tests:
    extends: .run_tests
    image: node:18.14.0-alpine

# run_tests-node-next:
#     extends: .run_tests
#     image: node:19.6.0-alpine
#     allow_failure: true
