image: docker:stable

variables:
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASS: test-pass
  POSTGRES_DB: testdb
  MONGO_CONN: "mongodb://mongo/dataplatform"

stages:
  - build
  - deploy

run_tests:
  stage: build
  image: gitlab.oict.cz:4567/data-platform/node-mongo:latest
  services:
    - gitlab.oict.cz:4567/data-platform/docker-postgis:10.5
    - mongo:4.0.5
  script:
    - npm install
    - npm run build
    - mongorestore --uri=$MONGO_CONN -d dataplatform ./test/data/dataplatform
    - export LOG_LEVEL=INFO
    - export MONGO_CONN=$MONGO_CONN
    - export POSTGRES_CONN=postgres://$POSTGRES_USER:$POSTGRES_PASS@$POSTGRES_HOST/$POSTGRES_DB
    - npm run code-coverage

build_image:
  stage: build
  script:
    - echo $CI_COMMIT_SHA > commitsha
    - docker build -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_PIPELINE_ID -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest .

registry_deployment:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_PIPELINE_ID && docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  only:
    refs:
      - master
      - development

api_documentation_deployment:
  stage: deploy
  image: ruby:2.6
  script:
    - gem install apiaryio
    - P='<!-- __DATE__ -->';D='('`date '+%m\/%d\/%Y %H:%M'`' - v'$CI_PIPELINE_ID')';sed -i "s/$P/$D/g" docs/apiary_docs.apib
    - apiary publish --path="docs/apiary_docs.apib" --api-name="outputgateway"
  only:
    changes:
      - docs/apiary_docs.apib
    refs:
      - master

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r docs/typedoc .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
    - master

