FORMAT: 1A

# Golemio API

<img src="https://storage.golemio.cz/golemiocz/images/golemioapi_logos.png" alt="Logos" />

**⚠️ Upozornění! Od 1. 11. 2022 dochází k migraci API dokumentace na nové Swagger UI. Odkazy na aktuální dokumentaci jednotlivých endpointů naleznete vždy pod danou kategorií.**

**⚠️ Warning! As of November 1, 2022, the API documentation is being migrated to the new Swagger UI. Links to the current documentation of individual endpoints can always be found under the given category.**

> Swagger UI dokumentace:
> - [Main Golemio Output Gateway API](https://api.golemio.cz/v2/docs/openapi/)
> - [Open Data Golemio Output Gateway API](https://api.golemio.cz/v2/docs/public-openapi/)
> - [Public Transport Golemio Output Gateway API](https://api.golemio.cz/v2/pid/docs/openapi/)

Toto je dokumentace REST API projektu pražské datové platformy Golemio.

Veškeré dotazy prosím směřujte na [golemio@operatorict.cz](mailto:golemio@operatorict.cz?subject=golemioapiv1)

Dokumentace je v anglickém jazyce. Více informací o projektu naleznete na [www.golemio.cz](https://www.golemio.cz/).

## Description

**This is documentation of RESTful API of Golemio Prague Data Plaform project.**

Support is avalailable via [golemio@operatorict.cz](mailto:golemio@operatorict.cz?subject=golemioapiv1)

More about project Golemio at [www.golemio.cz](https://www.golemio.cz/).

## Versions

- **v0.1 (current)** <!-- __DATE__ -->

## General info

### Authorization

Generate your own token at [api.golemio.cz/api-keys](https://api.golemio.cz/api-keys).

**Use the token as value of `X-Access-Token` header.**

### Usage

#### Pagination

**The API returns maximum count of 10000 objects / rows for one request. You can specify lower number by adding `?limit` URL parameter.**

This may vary depending on the specific route, read the description of the parameters for each route.
You can only get more data using multiple reqeusts with `?limit&offset` parameters, read examples below.

#### Requests rate

**By default, each API key has a rate-limit set of 10000 requests per 10 seconds.**

#### Open Data

![golemioapi-opendata-badge](https://img.shields.io/badge/opendata-available-green)

This badge means it is available for public use as Open Data.

### General responses

| Response code | Description |
| - | - |
| `403: Forbidden` | Your API-Key don't have the necessary rights to the specific route (or specific route+parameters combination). Permissions are explicitly granted for each API-key per route. |
| | API can also return `403` to a call with invalid parameters (for example, you can have permission to view only `route/?type=1` and try to call `route/?type=2`, you can get a `403`)
| `404`: Not found | Non-existing routes or not-found resource returns. |
| `429: Too Many Requests` | API can also return  if you exceed you rate-limit (again, rate-limits are explicitly granted for each API-key individually). |
| `200`: Success | Otherwise success responses |

### General Parameters

Following parameters are applicaple for most of the resoures/routes. All parameters are optional. Don't copy-paste example API calls with all parameters if you don't need them.

| Parameter | Description |
| - | - |
| `latlng` | location, API performs geo-spatial search to retrieve data close to the location (sorts data by proximity); Latitude and Longitude separated by comma, latitude first |
| `range` | filters the results by their distance from provided latlng in meters (range query); is ignored when latlng is not specified |
| `districts` | filters by Prague city districts (in array format - eg. `districts[]=praha7&districts[]=praha6`) |
| `limit` | pagination - limits number of retrieved items (kNN query) |
| `offset` | pagination - mumber of the first items that are skipped |
| `updatedSince` | filters all results with lower `updated_at` than this parameter, in ISO8601 format |
| `ids` | filters by individual entity IDs (in array format - eg. `ids[]=1&ids[]=3`) |

All parameters are optional and are evaluated at the same time as AND (only results meeting all the conditions at the same time are returned).

Multiple values of the same parameter of type array are evaluated as OR (results meeting at least one condition are returned). Eg. `districts` or `ids`.

### Possible headers

| header | description |
| - | - |
| `Cache-Control` | Server-side caching is used by default. If this request header value is set to `no-cache`, always fresh data are served and the cache is not used. |
| `If-None-Match` | Weak E-Tag implementation is used for additional caching. | API returns `ETag` response header, example: W/"21cf-vMBh8gdzFfYJ4qSGaPA6/dooVV0" | If the `If-None-Match` request header value matches the current `ETag`, 304 response (cached) is sent. ETag value changes everytime data are changed. This may save data traffic (as the same unchanged data are not sent) but is not faster on the server side. You should not need this unless you're repeatedly querying the same data and trying to save network traffic. |

## Example requests

| URL | description |
| - | - |
| `/parkings/?limit=10&offset=10` | get 10th - 20th record (2nd page of 10 elements each when paginating) (using `limit` and `offset` parameters) |

👉 More examples at [operator-ict.gitlab.io/golemio/documentation/en/tutorials/golemioapi](https://operator-ict.gitlab.io/golemio/documentation/en/tutorials/golemioapi/)

# Group Air Quality 🌦

**Air Quality Stations CHMI [/airqualitystations]**

API documentation was moved to [api.golemio.cz/v2/docs/public-openapi/](https://api.golemio.cz/v2/docs/public-openapi/#/Air%20Quality%20%F0%9F%8C%A6)

## Meteosensors TSK [/meteosensors]

![golemioapi-opendata-badge](https://img.shields.io/badge/opendata-available-green)

### GET All Meteosensors TSK [GET /meteosensors/{?latlng,range,districts,limit,offset,updatedSince}]

+ Parameters

    + latlng: `50.124935,14.457204` (optional, string) - Sorting by location (Latitude and Longitude separated by comma, latitude first).
    + range: 5000 (optional, number) - Filter by distance from latlng in meters (range query). Depends on the latlng parameter.
    + districts: `praha-4` (optional, array) - Filter by Prague city districts (slug) separated by comma.
    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + updatedSince: `2019-05-18T07:38:37.000Z` (optional, string) - Filters out all results with older updated_at than this parameter

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (object)
        + type: FeatureCollection (string, required)
        + features (array)
            + (Feature Point)
                + properties (Meteosensor)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Meteosensor TSK [GET /meteosensors/{id}]

+ Parameters

    + id: 531801 (number) - Identifier of the meteosensor.

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Feature Point)
        + properties (Meteosensor)

+ Response 404 (application/json; charset=utf-8)

    + Attributes (Error)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

# Group Parking 🅿️

**Parking Spaces [/parking]**

API documentation was moved to [api.golemio.cz/v2/docs/public-openapi/](https://api.golemio.cz/v2/docs/public-openapi/#/%F0%9F%85%BF%EF%B8%8F%20Parking)

## Parking Lots [/parkings]

![golemioapi-deprecated-badge](https://img.shields.io/badge/-Deprecated-red)

This endpoint is now deprecated. Please use Parking Spaces endpoints.

| Enum value | Parking type description (cs) | Parking type description (en) |
| - | - | - |
| 1 | P+R parkoviště | P+R parking |
| 2 | placené parkoviště | paid private parking |

### GET All Parking Lots [GET /parkings/{?latlng,range,districts,limit,offset,updatedSince}]

+ Parameters

    + latlng: `50.124935,14.457204` (optional, string) - Sorting by location (Latitude and Longitude separated by comma, latitude first).
    + range: 5000 (optional, number) - Filter by distance from latlng in meters (range query). Depends on the latlng parameter.
    + districts: `praha-4` (optional, array) - Filter by Prague city districts (slug) separated by comma.
    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + updatedSince: `2019-05-18T07:38:37.000Z` (optional, string) - Filters all results with older updated_at than this parameter

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (object)
        + type: FeatureCollection (string, required)
        + features (array)
            + (Feature Point)
                + properties (Parking)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Parking Lots History [GET /parkings/history/{?from,to,limit,offset,sensorId}]

+ Parameters

    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + from: `2019-05-16T04:27:58.000Z` (optional, string) - Date in ISO8601, limits data measured from this datetime
    + to: `2019-05-18T04:27:58.000Z` (optional, string) - Date in ISO8601, limits data measured up until this datetime
    + sensorId: `12345` (optional, string) - Limits data measured up by sensor with this id (parameter `id` of the parking)

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array)
        + (Parkings History)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Parking Lot [GET /parkings/{id}]

+ Parameters

    + id: 534015 (number) - Identifier of the parking.

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Feature Point)
        + properties (Parking deprecated)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)


## Parking Zones [/parkingzones]

![golemioapi-deprecated-badge](https://img.shields.io/badge/-Deprecated-red)

This endpoint is now deprecated. Please use Parking Spaces endpoints.

GeoJSON format of all polygons for on-street parking zones. Tariffs for each zone with valid prices per hour in CZK.

| Category code | Category description (cs) | Category description (en) |
| - | - | - |
| RES | rezidentní zóna (modrá) | residential area (blue) |
| VIS | návštěvnická zóna area (oranžová) | visitor area (orange) |
| MIX | smížená zóna area (fialová) | mixed area (purple) |
| KOM | zóna pro ZTP (šedá) | area only with ZTP or forbidden (grey) |

### GET All Parking Zones [GET /parkingzones/{?latlng,range,districts,limit,offset,updatedSince}]

+ Parameters

    + latlng: `50.124935,14.457204` (optional, string) - Sorting by location (Latitude and Longitude separated by comma, latitude first).
    + range: 5000 (optional, number) - Filter by distance from latlng in meters (range query). Depends on the latlng parameter.
    + districts: `praha-4` (optional, array) - Filter by Prague city districts (slug) separated by comma.
    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + updatedSince: `2019-05-18T07:38:37.000Z` (optional, string) - Filters all results with older updated_at than this parameter

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

       + Attributes (object)
        + type: FeatureCollection (string, required)
        + features (array)
            + (Feature Polygon)
                + properties (Parking Zone)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Parking Zone [GET /parkingzones/{parkingzoneCode}]

+ Parameters

    + parkingzoneCode: `P1-0101` (string) - Identifier of the parking zone.

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Feature Polygon)
        + properties (Parking Zone)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Parking Zones Tariffs [GET /parkingzones/tariffs]

+ Request (application/json; charset=utf-8)

    + Headers

            x-api-key: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9...

+ Response 200 (application/json; charset=utf-8)

    + Attributes (array)
        + (Parking Zone Tariff)


# Group Public Space 🏡

**Gardens [/gardens]**

API documentation was moved to [api.golemio.cz/v2/docs/public-openapi/](https://api.golemio.cz/v2/docs/public-openapi/#/%F0%9F%8C%B3%20Gardens)

**Medical Institutions [/medicalinstitutions]**

API documentation was moved to [api.golemio.cz/v2/docs/public-openapi/](https://api.golemio.cz/v2/docs/public-openapi/#/%F0%9F%8F%A5%20Medical%20Institutions)

**Municipal Authorities [/municipalauthorities]**

API documentation was moved to [api.golemio.cz/v2/docs/public-openapi/](https://api.golemio.cz/v2/docs/public-openapi/#/%F0%9F%8F%9B%20Municipal%20Authorities)

**Municipal Police Stations [/municipalpolicestations]**

API documentation was moved to [api.golemio.cz/v2/docs/public-openapi/](https://api.golemio.cz/v2/docs/public-openapi/#/%F0%9F%91%AE%20Municipal%20Police%20Stations)

**Playgrounds [/playgrounds]**

API documentation was moved to [api.golemio.cz/v2/docs/public-openapi/](https://api.golemio.cz/v2/docs/public-openapi/#/%F0%9F%8F%B8%20Playgrounds)

## Prague City Districts [/citydistricts]

![golemioapi-opendata-badge](https://img.shields.io/badge/opendata-available-green)

### GET All Districts [GET /citydistricts/{?latlng,range,limit,offset,updatedSince}]

+ Parameters


    + latlng: `50.124935,14.457204` (optional, string) - Sorting by location (Latitude and Longitude separated by comma, latitude first).
    + range: 5000 (optional, number) - Filter by distance from latlng in meters (range query). Depends on the latlng parameter.
    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + updatedSince: `2019-05-18T07:38:37.000Z` (optional, string) - Filters all results with older updated_at than this parameter

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (object)
        + type: FeatureCollection (string, required)
        + features (array)
            + (Feature Polygon)
                + properties (City District)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET District [GET /citydistricts/{id}]

+ Parameters

    + id: `praha-1` (string) - Identifier or slug of the city district.

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Feature Polygon)
        + properties (City District)


+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

## Public Toilets [/publictoilets]

![golemioapi-deprecated-badge](https://img.shields.io/badge/-Deprecated-red)

This endpoint is now deprecated.

### GET All Public Toilets [GET /publictoilets/{?latlng,range,districts,limit,offset,updatedSince}]

+ Parameters

    + latlng: `50.124935,14.457204` (optional, string) - Sorting by location (Latitude and Longitude separated by comma, latitude first).
    + range: 5000 (optional, number) - Filter by distance from latlng in meters (range query). Depends on the latlng parameter.
    + districts: `praha-4` (optional, array) - Filter by Prague city districts (slug) separated by comma.
    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + updatedSince: `2019-05-18T07:38:37.000Z` (optional, string) - Filters all results with older updated_at than this parameter

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (object)
        + type: FeatureCollection (string, required)
        + features (array)
            + (Feature Point)
                + properties (Public Toilet)


+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Public Toilet [GET /publictoilets/{id}]

+ Parameters

    + id: 72 (number) - Identifier of the public toilet.

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Feature Point)
        + properties (Public Toilet)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

## Municipal Libraries [/municipallibraries]

![golemioapi-opendata-badge](https://img.shields.io/badge/opendata-available-green)

### GET All Municipal Libraries [GET /municipallibraries/{?latlng,range,districts,limit,offset,updatedSince}]

+ Parameters

    + latlng: `50.124935,14.457204` (optional, string) - Sorting by location (Latitude and Longitude separated by comma, latitude first).
    + range: 5000 (optional, number) - Filter by distance from latlng in meters (range query). Depends on the latlng parameter.
    + districts: `praha-4` (optional, array) - Filter by Prague city districts (slug) separated by comma.
    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + updatedSince: `2019-05-18T07:38:37.000Z` (optional, string) - Filters all results with older updated_at than this parameter

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (object)
        + type: FeatureCollection (string, required)
        + features (array)
            + (Feature Point)
                + properties (Municipal Library)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Municipal Library [GET /municipallibraries/{id}]

+ Parameters

    + id: 2 (number) - Identifier of the library.

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Feature Point)
        + properties (Municipal Library)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)


# Group Public Transport 🚋

API documentation was moved to [api.golemio.cz/v2/pid/docs/openapi/](https://api.golemio.cz/v2/pid/docs/openapi/)

# Group Traffic 🚘

## Shared Cars  [/sharedcars]

![golemioapi-opendata-badge](https://img.shields.io/badge/opendata-available-green)

| Enum value | Fuel description (cs) | Fuel description (en) |
|- |- |- |
| 1 | benzin | gas |
| 2 | nafta | diesel |
| 3 | LPG | LPG |
| 4 | elektřina | electric |
| 5 | hybrid | hybrid |
| 6 | CNG |CNG  |
| 7 | jiný | other |
| 0 | neznámý | unknown |

| Enum value | Availability description (cs) | Availability description (en) |
|- |- |- |
| 1 | ihned | now |
| 2 | dle domluvy s provozovatelem | upon the agreement with provider |

### GET All Shared Cars [GET /sharedcars/{?latlng,range,limit,offset,updatedSince}]

+ Parameters

    + latlng: `50.124935,14.457204` (optional, string) - Sorting by location (Latitude and Longitude separated by comma, latitude first).
    + range: 5000 (optional, number) - Filter by distance from latlng in meters (range query). Depends on the latlng parameter.
    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + updatedSince: `2019-05-18T07:38:37.000Z` (optional, string) - Filters all results with older updated_at than this parameter

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

   + Attributes (object)
        + type: FeatureCollection (string, required)
        + features (array)
            + (Feature Point)
                + properties (Shared Car)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Shared Car [GET /sharedcars/{id}]

+ Parameters

    + id: `1BF8210` (string) - Identifier of the car.

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Feature Point)
        + properties (Shared Car)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)


## Bicycle Parkings [/bicycleparkings]

![golemioapi-deprecated-badge](https://img.shields.io/badge/-Deprecated-red)

This endpoint is now deprecated.

### GET All Bicycle Parkings [GET /bicycleparkings/{?latlng,range,limit,offset,updatedSince}]

+ Parameters

    + latlng: `50.124935,14.457204` (optional, string) - Sorting by location (Latitude and Longitude separated by comma, latitude first).
    + range: 5000 (optional, number) - Filter by distance from latlng in meters (range query). Depends on the latlng parameter.
    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + updatedSince: `2019-05-18T07:38:37.000Z` (optional, string) - Filters all results with older updated_at than this parameter

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

   + Attributes (object)
        + type: FeatureCollection (string, required)
        + features (array)
            + (Feature Point)
                + properties (Bicycle Parking)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Bicycle Parking [GET /bicycleparkings/{id}]

+ Parameters

    + id: `282743091` (number) - Identifier of the bicycle parking.

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Feature Point)
        + properties (Bicycle Parking)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

## Bicycle Counters [/bicyclecounters]

![golemioapi-opendata-badge](https://img.shields.io/badge/opendata-available-green)

https://api.golemio.cz/v2/docs/public-openapi/#/Bicycle%20Counter

## Traffic Cameras [/trafficcameras]

![golemioapi-deprecated-badge](https://img.shields.io/badge/-Deprecated-red)

This endpoint is now deprecated.

### GET All Traffic Cameras [GET /trafficcameras/{?latlng,range,districts,limit,offset,updatedSince}]

+ Parameters

    + latlng: `50.124935,14.457204` (optional, string) - Sorting by location (Latitude and Longitude separated by comma, latitude first).
    + range: 5000 (optional, number) - Filter by distance from latlng in meters (range query). Depends on the latlng parameter.
    + districts: `praha-4` (optional, array) - Filter by Prague city districts (slug) separated by comma.
    + limit: 10 (optional, number) - Limits number of retrieved items. The maximum is 10000 (default value).
    + offset: 0 (optional, number) - Number of the first items that are skipped.
    + updatedSince: `2019-05-18T07:38:37.000Z` (optional, string) - Filters all results with older updated_at than this parameter

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

   + Attributes (object)
        + type: FeatureCollection (string, required)
        + features (array)
            + (Feature Point)
                + properties (Traffic Camera)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)

### GET Traffic Camera [GET /trafficcameras/{id}]

+ Parameters

    + id: 404032 (number) - Identifier of the camera.

+ Request (application/json; charset=utf-8)

    + Headers

            x-access-token: YOUR_ACCESS_TOKEN

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Feature Point)
        + properties (Traffic Camera)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (Error)

+ Response 403 (application/json; charset=utf-8)
    + Attributes (403 Error)


# Group Waste ♻️

**Sorted Waste Stations [/sortedwastestations/]**

API documentation was moved to [api.golemio.cz/v2/docs/public-openapi/](https://api.golemio.cz/v2/docs/public-openapi/#/%E2%99%BB%EF%B8%8F%20Waste%20Collection)

**Waste Collection Yards [/wastecollectionyards]**

API documentation was moved to [api.golemio.cz/v2/docs/public-openapi/](https://api.golemio.cz/v2/docs/public-openapi/#/%E2%99%BB%EF%B8%8F%20Waste%20Collection%20Yards)






# Data structure

## Point (array[number])

+ 14.4633 (number, required) - longitude
+ 50.07827 (number, required) - latitude

## Polygon (array[Point])

+ (Point, required)
+ (Point, required)
+ (Point, required)
+ (Point, required) - Four points make basic polygon
+ (Point, optional)

## Multi Polygon (array[Polygon])

+ (Polygon, required) - First list is an enclosing polygon
+ (Polygon, optional) - Next ones are cut out areas

## Error (object)
+ error_message: `Not Found` (required, string)
+ error_status: 404 (required, number)

## 403 Error (object)
+ error_message: `Forbidden` (required, string)
+ error_status: 403 (required, number)

## Feature Point (object)

+ geometry (required)
    + type: Point (string, required)
    + coordinates (Point, required)
+ properties (object, required)
+ type: Feature (string, required)

## Feature Polygon (object)

+ geometry (required)
    + type: Polygon (required, string)
    + coordinates (array[Polygon], required)
+ properties (object, required)
+ type: Feature (required, string)

## Address (object)

+ address_formatted: `Dělnická 213/10, 17000 Praha-Holešovice, Česko` (string)
+ street_address: `Dělnická 213/10` (string)
+ postal_code: `17000` (string)
+ address_locality: `Praha` (string)
+ address_region: `Holešovice` (string)
+ address_country: `Česko` (string)

## Bicycle Parking (object)

+ district: `praha-4` (string)
+ id: 6239570526 (number, required)
+ tags (array[Bicycle Parking Tag])
+ updated_at: `2019-05-18T07:38:37.000Z` (string)

## Bicycle Parking Tag (object)

+ id: `capacity` (string, required)
+ value: `2` (string)

## City District (object)

+ id: 538124 (number, required)
+ name: `Praha-Březiněves` (string, required)
+ slug: `praha-brezineves` (string, required)
+ updated_at: `2019-05-18T07:38:37.000Z` (string)

## Meteosensor (object)

+ air_temperature: 18.95 (number)
+ humidity: 31 (number)
+ id: 531802 (number, required)
+ last_updated: 1556806121000 (number, required)
+ name: `Bulhar` (string, required)
+ road_temperature: 34.55 (number)
+ updated_at: `2019-05-18T07:38:37.000Z` (string)
+ wind_direction: 230 (number)
+ wind_speed: 2.08 (number)
+ district: `praha-2` (string)

## Municipal Library (object)

+ address (Address)
+ district: `praha-1` (string)
+ id: 2 (number, required)
+ email: `knihovna@mlp.cz` (string, required)
+ name: `Barrandov` (string, required)
+ opening_hours (array[Opening Hours])
+ sections_and_departments (array[Municipal Library Section])
+ services (array[Municipal Library Service])
+ telephone: `+420 770 130 262` (string, required)
+ updated_at: `2020-06-30T14:16:45.891Z` (string, required)
+ web: `https://www.mlp.cz/cz/pobocky/barrandov/` (string, required)

## Municipal Library Section

+ id: `code-8` (string, required)
+ name: `Oddělení pro děti a mládež` (string, required)
+ type: `tag` (string, optional, nullable)
+ url (string, optional, nullable)

## Municipal Library Service

+ description: `Bezbariérový přístup pro vozíčkáře i rodiče s kočárky` (string, optional, nullable)
+ id: 3 (number, required)
+ name: `Bezbariérový přístup` (string, required)

## Opening Hours (object)

+ closes: `12:00` (string)
+ day_of_week: `Monday` (string)
+ description (string)
+ is_default (boolean)
+ opens: `08:00` (string)
+ valid_from: `2020-06-30T22:00:00.000Z` (string, optional, nullable)
+ valid_through: `2020-08-30T22:00:00.000Z` (string, optional, nullable)

## Parking deprecated (object)

+ parking_type (Parking Type)
+ id: `534012` (number, required)
+ name: `Skalka 1` (string, required)
+ num_of_free_places: 0 (number, required)
+ num_of_taken_places: 63 (number, required)
+ updated_at: `2019-05-18T07:38:37.000Z` (string)
+ total_num_of_places: 63 (number, required)
+ average_occupancy (Parking Occupancy)
+ district: `praha-10` (string)
+ address (Address)
+ last_updated: 1556868553000 (number)
+ payment_link: `https://ke-utc.appspot.com/static/onstreet.html?shortname=143` (string, optional, nullable)
+ payment_shortname: `143` (string, optional, nullable)

## Parking (object)

+ parking_type (Parking Type)
+ id: `tsk-143` (string, required)
+ name: `Skalka 1` (string, required)
+ num_of_free_places: 0 (number, required)
+ num_of_taken_places: 63 (number, required)
+ updated_at: `2019-05-18T07:38:37.000Z` (string)
+ total_num_of_places: 63 (number, required)
+ average_occupancy (Parking Occupancy)
+ district: `praha-10` (string)
+ address (Address)
+ last_updated: 1556868553000 (number)
+ payment_link: `https://ke-utc.appspot.com/static/onstreet.html?shortname=143` (string, optional, nullable)
+ payment_shortname: `143` (string, optional, nullable)

## Parkings History (object)

+ id: 534012 (number, required)
+ num_of_free_places: 0 (number, required)
+ num_of_taken_places: 63 (number, required)
+ updated_at: `2019-05-18T07:38:37.000Z` (string) - timestamp of requesting vendor API
+ total_num_of_places: 63 (number, required)
+ last_updated: 1556868553000 (number) - timestamp of measurement by vendor

## Parking Occupancy (object)

+ 0 (Parking Occupancy Day)
+ 1 (Parking Occupancy Day)
+ 2 (Parking Occupancy Day)
+ 3 (Parking Occupancy Day)
+ 4 (Parking Occupancy Day)
+ 5 (Parking Occupancy Day)
+ 6 (Parking Occupancy Day)

## Parking Occupancy Day
+ 00: 32 (number)
+ 01: 57 (number)
+ 02: 17 (number)
+ 03: 47 (number)
+ 04: 117 (number)
+ 05: 5 (number)
+ 06: 59 (number)
+ 07: 59 (number)
+ 08: 159 (number)
+ 09: 59 (number)
+ 10: 59 (number)
+ 11: 59 (number)
+ 12: 59 (number)
+ 13: 59 (number)
+ 14: 59 (number)
+ 15: 59 (number)
+ 16: 99 (number)
+ 17: 59 (number)
+ 18: 59 (number)
+ 19: 59 (number)
+ 20: 67 (number)
+ 21: 32 (number)
+ 22: 59 (number)
+ 23: 59 (number)

## Parking Type (object)

+ description: `P+R parkoviště` (string)
+ id: 1 (number, required)

## Parking Zone (object)

+ id: `p1-0111` (string, required)
+ midpoint: 14.3933334097666, 50.0906432052142 (array[number], required)
+ name: `Rezidentní úsek - P1-0111` (string, required)
+ northeast: 14.3933334097666, 50.0906432052142 (array[number], required)
+ number_of_places: 31 (number, required)
+ payment_link: `https://ke-utc.appspot.com/static/onstreet.html?shortname=P1-0111` (string)
+ southwest: 14.3933334097666, 50.0906432052142 (array[number], required)
+ updated_at: `2019-05-18T07:38:37.000Z` (string)
+ type (Parking Zone Type)
+ zps_id: 3312 (number, optional, nullable)
+ zps_ids (array[number], optional)
+ tariff_ids: `d1bc6cae620aa65200d47b61cf483299ca03d6c9` (array[string])
+ tariffs_text: `Po-Ne 08:00-19:59 80 Kč/hod. (max. 1 hod.); Po-Ne 20:00-05:59 80 Kč/hod. (max. 1 hod.); Po-Ne (ve svátek) 08:00-05:59 80 Kč/hod. (max. 1 hod.)` (string)

## Parking Zone Tariff Schedule (object)

+ days: Saturday, Sunday (array[string])
+ tariff (array[Parking Zone Tariff])

## Parking Zone Tariff (object)

+ time_from: `PT8H` (string)
+ pay_at_holiday: `false` (boolean)
+ max_parking_time: `PT1H` (string)
+ time_to: `PT19H59M` (string)
+ price_per_hour: 80 (number)
+ max_price: 0 (number)
+ divisibility: `PT15M` (string)
+ tariff_id: `d1bc6cae620aa65200d47b61cf483299ca03d6c9` (array[string])

## Parking Zone Type (object)

+ description: `Rezidentní úsek` (string)
+ id: 1 (number, required)

## Parking category (enum)
+ `park_and_ride`
+ `park_paid_private`
+ `zone_residential`
+ `zone_visitors`
+ `zone_mixed`
+ `zone_other`

## Parking Space (object)

+ id: `korid-20` (string, required)
+ source: `korid` (string, required)
+ source_id: `20` (string, required)
+ data_provider: `www.korid.cz` (string, nullable)
+ name: `Husova (u nemocnice)` (string, required)
+ category: (Parking category, nullable)
+ date_modified: `2020-05-18T07:38:37.000Z` (string, nullable)
+ address: (Address, nullable)
+ area_served: null (string, nullable)
+ payment_url: `https://payment.com/link.html` (string, nullable)
+ total_spot_number: 180 (number, required)
+ tariff_id: `b184865e-5a5e-5465-abc1-4fab6bc56a77` (string, nullable)
+ valid_from: `2020-05-31T00:00:00.000Z` (string, nullable)
+ valid_to: `2022-05-31T00:00:00.000Z` (string, nullable)

## Parking Measurement (object)

+ id: `10168955` (string, required)
+ source: `korid` (string, required)
+ source_id: `20` (string, required)
* parking_id: `korid-20` (string)
+ available_spot_number: 5 (number, required)
+ closed_spot_number: 0 (number, required)
+ occupied_spot_number: 8 (number, required)
+ total_spot_number: 13 (number, required)
+ date_modified: `2021-02-26T12:02:46.188Z` (string, required)

## Parking Space Tariff Charge (object)
+ charge: 20 (number, required)
+ charge_order_index: 0 (number, required)
+ charge_type: `minimum` (string, nullable)
+ charge_interval: 1800 (number, nullable)
+ max_iterations_of_charge: 1 (number, nullable)
+ min_iterations_of_charge: 1 (number, nullable)
+ start_time_of_period: `Mon-Fri 09:00` (string, nullable)
+ end_time_of_period: `Mon-Sun 14:30` (string, nullable)

## Parking Space Tariff (object)

+ tariff_id: `b184865e-5a5e-5465-abc1-4fab6bc56a77` (string, required)
+ source: `korid` (string, required)
+ last_updated: `2020-10-12T15:19:21+02:00` (string, required)
+ payment_mode: `""` (string, required)
+ payment_additional_description: `Parkování Liberec` (string, nullable)
+ free_of_charge: false (boolean, required)
+ url_link_address: `https://parking.liberec.cz/` (string, required)
+ charge_band_name: `A` (string, required)
+ accepts_payment_card: true (boolean, nullable)
+ accepts_cash: false (boolean, nullable)
+ accepts_mobile_payment: false (boolean, nullable)
+ charge_currency: `CZK` (string, required)
+ allowed_vehicle_type: `carSharing, taxi` (string, nullable)
+ allowed_fuel_type: `electricity, petrol, lpg` (string, nullable)
+ charge: (array[Parking Space Tariff Charge])

## Public Toilet (object)

- id: 18 (number, required)
- opened: `10:00 - 21:00` (string)
- price: `zdarma` (string)
- updated_at: `2019-05-18T07:38:37.000Z` (string)
- district: `praha-13` (string)
- address (Address)

## Shared Car (object)

+ availability (Shared Car Availability)
+ company (Shared Car Company)
+ fuel (Shared Car Fuel)
+ id: `9B99149` (string, required)
+ name: `Škoda Citigo` (string, required)
+ res_url: `https://autonapul.zemtu.com/app/#/?rz=9B99149` (string, required)
+ updated_at: `2019-05-18T07:38:37.000Z` (string)

## Shared Car Availability (object)

+ description: `ihned` (string)
+ id: 1 (number, required)

## Shared Car Company (object)

+ email: `autonapul@autonapul.cz` (string)
+ name: `Autonapůl` (string, required)
+ phone: `+420 778 470 898` (string)
+ web: `https://www.autonapul.cz/` (string, required)

## Shared Car Fuel (object)

+ description: `benzín` (string)
+ id: 1 (number, required)

## Traffic Camera (object)

+ image (Traffic Camera Image)
+ id: 606748 (number, required)
+ last_updated: 1557229128000 (number, required) - timestamp of last update by vendor
+ name: `DP - Kobylisy C - BUS MHD DP` (string, required)
+ updated_at: `2019-05-18T07:38:37.000Z` (string) - timestamp of requesting vendor API
+ district: `praha-8` (string)
+ address (Address)

## Traffic Camera Image (object)

+ data: `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQAB.........pgf//Z` (string)
+ file_size: 20072 (number, required)
+ type: `image/jpeg` (string)
+ url: `http://www.tsk-praha.cz/cams/cam606748.jpg?1557229128000` (string, required)
