export { airQualityRouter } from "@golemio/air-quality-stations/dist/output-gateway";
export { bicycleCountersRouter } from "@golemio/bicycle-counters/dist/output-gateway";
export { cityDistrictsRouter } from "@golemio/city-districts/dist/output-gateway";
export { exportingModuleRouter } from "@golemio/exporting-module/dist/output-gateway";
export { fcdRouter } from "@golemio/fcd/dist/output-gateway";
export { gardensRouter } from "@golemio/gardens/dist/output-gateway";
export { medicalInstitutionsRouter } from "@golemio/medical-institutions/dist/output-gateway";
export { municipalAuthoritiesRouter } from "@golemio/municipal-authorities/dist/output-gateway";
export { parkingZonesRouter } from "@golemio/parking-zones/dist/output-gateway";
export { playgroundsRouter } from "@golemio/playgrounds/dist/output-gateway";
export { sharedBikesRouter, gbfsRouter as sharedBikesGbfsRouter } from "@golemio/shared-bikes/dist/output-gateway";
export { sortedWasteRouterPg } from "@golemio/sorted-waste-stations/dist/output-gateway/sorted-waste-stations-pg";
export { parkingsRouter } from "@golemio/parkings/dist/output-gateway";
export { pedestriansRouter } from "@golemio/flow/dist/output-gateway";
export { trafficRouter } from "@golemio/ndic/dist/output-gateway";
export { wasteCollectionYardsRouter } from "@golemio/waste-collection-yards/dist/output-gateway";
export { municipalPoliceStationsRouter } from "@golemio/municipal-police-stations/dist/output-gateway";
